language: python
python:
   - 3.7

install:
   - pip install importlib-metadata==4.12
   - pip install -r requirements.txt

script:
   - coverage run --source="." manage.py test
after_script:
   - coveralls

deploy:
  provider: elasticbeanstalk

  region: us-west-2
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-832394055959
  on:
    repo: yalexublue/swe1-app2
    branch: main