language: python
python:
   - 3.7
install:
   - pip install -r requirements.txt
deploy:
  provider: elasticbeanstalk
  access_key_id: ${{ secrets.ACCESS_KEY_ID }}
  secret_access_key:
    secure: ${{ secrets.SECRET_KEY }}
  region: us-west-2
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-832394055959
  on:
    repo: yalexublue/swe1_app2
    branch: main
script:
   - flake8 .
   - black --check .
   - coverage run --source=ebdjango,polls manage.py test
